# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

linpredcompute <- function(X, nsites, p, beta, offset) {
    .Call('CARBayes_linpredcompute', PACKAGE = 'CARBayes', X, nsites, p, beta, offset)
}

quadform <- function(Wtriplet, Wtripletsum, n_triplet, nsites, phi, theta, rho) {
    .Call('CARBayes_quadform', PACKAGE = 'CARBayes', Wtriplet, Wtripletsum, n_triplet, nsites, phi, theta, rho)
}

binomialcarupdate <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, failures, trials, phi_tune, rho, offset, missind) {
    .Call('CARBayes_binomialcarupdate', PACKAGE = 'CARBayes', Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, failures, trials, phi_tune, rho, offset, missind)
}

binomialbetaupdateMALA <- function(X, nsites, p, beta, offset, y, failures, trials, prior_meanbeta, prior_varbeta, missind, nblock, beta_tune, block_list) {
    .Call('CARBayes_binomialbetaupdateMALA', PACKAGE = 'CARBayes', X, nsites, p, beta, offset, y, failures, trials, prior_meanbeta, prior_varbeta, missind, nblock, beta_tune, block_list)
}

binomialbetaupdateRW <- function(X, nsites, p, beta, offset, y, failures, prior_meanbeta, prior_varbeta, missind, beta_tune) {
    .Call('CARBayes_binomialbetaupdateRW', PACKAGE = 'CARBayes', X, nsites, p, beta, offset, y, failures, prior_meanbeta, prior_varbeta, missind, beta_tune)
}

binomialindepupdate <- function(nsites, theta, sigma2, y, failures, trials, theta_tune, offset, missind) {
    .Call('CARBayes_binomialindepupdate', PACKAGE = 'CARBayes', nsites, theta, sigma2, y, failures, trials, theta_tune, offset, missind)
}

poissonindepupdate <- function(nsites, theta, sigma2, y, theta_tune, offset, missind) {
    .Call('CARBayes_poissonindepupdate', PACKAGE = 'CARBayes', nsites, theta, sigma2, y, theta_tune, offset, missind)
}

poissonbetaupdateMALA <- function(X, nsites, p, beta, offset, y, prior_meanbeta, prior_varbeta, missind, nblock, beta_tune, block_list) {
    .Call('CARBayes_poissonbetaupdateMALA', PACKAGE = 'CARBayes', X, nsites, p, beta, offset, y, prior_meanbeta, prior_varbeta, missind, nblock, beta_tune, block_list)
}

poissonbetaupdateRW <- function(X, nsites, p, beta, offset, y, prior_meanbeta, prior_varbeta, missind, beta_tune) {
    .Call('CARBayes_poissonbetaupdateRW', PACKAGE = 'CARBayes', X, nsites, p, beta, offset, y, prior_meanbeta, prior_varbeta, missind, beta_tune)
}

poissoncarupdate <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, phi_tune, rho, offset, missind) {
    .Call('CARBayes_poissoncarupdate', PACKAGE = 'CARBayes', Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, phi_tune, rho, offset, missind)
}

gaussiancarupdate <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, rho, nu2, offset, missind) {
    .Call('CARBayes_gaussiancarupdate', PACKAGE = 'CARBayes', Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, rho, nu2, offset, missind)
}

binomialmcarupdate <- function(Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, trials, phioffset, denoffset, Sigmainv, rho, phi_tune, missind) {
    .Call('CARBayes_binomialmcarupdate', PACKAGE = 'CARBayes', Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, trials, phioffset, denoffset, Sigmainv, rho, phi_tune, missind)
}

poissonmcarupdate <- function(Wtriplet, Wbegfin, nsites, nvar, phi, Y, phioffset, denoffset, Sigmainv, rho, phi_tune, missind) {
    .Call('CARBayes_poissonmcarupdate', PACKAGE = 'CARBayes', Wtriplet, Wbegfin, nsites, nvar, phi, Y, phioffset, denoffset, Sigmainv, rho, phi_tune, missind)
}

