# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

linpredcompute <- function(X, nsites, p, beta, offset) {
    .Call('CARBayes_linpredcompute', PACKAGE = 'CARBayes', X, nsites, p, beta, offset)
}

quadform <- function(Wtriplet, Wtripletsum, n_triplet, nsites, phi, theta, rho) {
    .Call('CARBayes_quadform', PACKAGE = 'CARBayes', Wtriplet, Wtripletsum, n_triplet, nsites, phi, theta, rho)
}

binomialcarupdate <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, failures, phi_tune, rho, offset) {
    .Call('CARBayes_binomialcarupdate', PACKAGE = 'CARBayes', Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, failures, phi_tune, rho, offset)
}

binomialbetaupdate <- function(X, nsites, p, beta, proposal, offset, y, failures, prior_meanbeta, prior_varbeta) {
    .Call('CARBayes_binomialbetaupdate', PACKAGE = 'CARBayes', X, nsites, p, beta, proposal, offset, y, failures, prior_meanbeta, prior_varbeta)
}

binomialindepupdate <- function(nsites, theta, sigma2, y, failures, theta_tune, offset) {
    .Call('CARBayes_binomialindepupdate', PACKAGE = 'CARBayes', nsites, theta, sigma2, y, failures, theta_tune, offset)
}

poissonindepupdate <- function(nsites, theta, sigma2, y, theta_tune, offset) {
    .Call('CARBayes_poissonindepupdate', PACKAGE = 'CARBayes', nsites, theta, sigma2, y, theta_tune, offset)
}

poissonbetaupdate <- function(X, nsites, p, beta, proposal, offset, y, prior_meanbeta, prior_varbeta) {
    .Call('CARBayes_poissonbetaupdate', PACKAGE = 'CARBayes', X, nsites, p, beta, proposal, offset, y, prior_meanbeta, prior_varbeta)
}

poissoncarupdate <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, phi_tune, rho, offset) {
    .Call('CARBayes_poissoncarupdate', PACKAGE = 'CARBayes', Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, phi_tune, rho, offset)
}

gaussiancarupdate <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, rho, nu2, offset) {
    .Call('CARBayes_gaussiancarupdate', PACKAGE = 'CARBayes', Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, rho, nu2, offset)
}

